### ISSUE TITLE
smprocnewnoart-documentation

### ISSUE THREAD

**Issue by KonstantinosKouk** [igridchyn/lfp_online#1]
Good evening, I am working with smprocnewnoart and so far I couldn't find some documentation of what exactly are the processing steps of it and I do not want to just use things without understanding what I am doing. Would you by any chance have anything of help on this? 
Thanks a lot in advance!!

**Comment by igridchyn** [comment]
Hi, I am not using this program for processing my data, but everyone else in our lab does. So it might be useful to ask anyone else from the Csicsvari Lab. I have used smprocnewnoart couple of times few years ago, as far as I remember, you only need dat files (binary matrix channels X time) and a corresponding par file, the format of which is described below. Then you run 'smprocnew <basename>', e.g. 'smprocnew jc54-2411-0117'.

Create .par file for the day

- the .par files control the processing of data by other applications
- use regaamc8 to determine which channels should be included in the .par file
- if the last tetrode (channels 60-63) is included, omit channel 63 (the sync channel).
- here is what the contents of a .par file mean (actual .par file cannot contain comments)...

#== below is actual content of example par file ==#
64 16 # n_channels n_systembits
50 800. # sampling_rate(usec) dummy.
16 57 # n_tetrodes ch_with_sharpwave_no_ripple
4 0 1 2 3 # 1st_tet_n_chans tetrode_chan_numbers
3 5 6 7 # 2nd_tet_n_chans...
2 8 9 # 3rd_tet_n_chans...
3 12 13 14
4 16 17 18 19
1 20
4 24 25 26 27
4 28 29 30 31
4 32 33 34 35
4 36 37 38 39
4 40 41 42 43
3 45 46 47
4 48 49 50 51
3 53 54 55
4 56 57 58 59
3 60 61 62 # 16th_tet_n_chans tetrode_chan_numbers
2 # number of .dat files to process together
jc21-2002_23 # first .dat file (minus extension)
jc21-2002_24 # second .dat file, followed by carriage return
#== end of example par file ==#

Tip: to avoid any error while listing the recoding sessions, use:
$ ls *.dat >> jc54-2411-0117.par
->it will append name of each recoding sessions at the bottom of the .par file. Then just delete the extension .dat.
Do the same to create .desen file:
$ emacs jc54-2411-0117.desen
$ ls *.dat >> jc54-2411-0117.desen
-> Then just replace each session_name by your session_code (e.g. cb nr1, b 1, ...)

**Comment by KonstantinosKouk** [comment]
Thanks a lot! Would you have any suggestion of a person I would be able to contact and he/she will be willing to share some info of the prepocessing before clustering of single spikes? 
Thanks in advance

**Comment by igridchyn** [comment]
@KotsosWir3  You can ask Yosman, for example. The e-mail address can be found here: 
[https://ist.ac.at/en/research/life-sciences/csicsvari-group/#Team](https://ist.ac.at/en/research/life-sciences/csicsvari-group/#Team)

**Comment by KonstantinosKouk** [comment]
@igridchyn  Thank you very much for the help!
